%% BuildScenario.m

% Reset persistent point lists
finalMinimaList = [];
finalMinimaCount = 0;
finalVOList = [];
finalVOCount = 0;
finalCPList = [];
finalCPCount = 0;

% UAV Scenario
MyScenario = uavScenario("UpdateRate", 100, "ReferenceLocation", [0 0 0]);

% Ownship
MyOwnship = uavPlatform("UAV", MyScenario, ...
                        "ReferenceFrame", "ENU", ...
                        "InitialPosition", InitialPosition, ...
                        "InitialOrientation", InitialOrientation);
updateMesh(MyOwnship, "quadrotor", {1.5}, [0 0 1], eul2tform([0 0 pi]));

% Lidar
MaxRange = 7;
Horizontal_Res = 5;
Vertical_Res = 3;
Horizontal_Limits = [-180 180];
Vertical_Limits = [-15 15];

MyLidar = uavLidarPointCloudGenerator("UpdateRate", 10, ...
                                      "MaxRange", MaxRange, ...
                                      "RangeAccuracy", 3, ...
                                      "AzimuthResolution", Horizontal_Res, ...
                                      "ElevationResolution", Vertical_Res, ...
                                      "AzimuthLimits", Horizontal_Limits, ...
                                      "ElevationLimits", Vertical_Limits, ...
                                      "HasOrganizedOutput", true);

MySensor = uavSensor("Lidar", MyOwnship, MyLidar, ...
                     "MountingLocation", [0 0 -0.4], ...
                     "MountingAngles", [0 0 0]);

% Build Map

obs_colours    = [0.6 0.6 0.6];
ObstacleHeight = 12;
ObstaclesWidth = 3;

for i = 1:size(ObstaclePositions, 1)
    addMesh(MyScenario, "polygon", ...
        {[ObstaclePositions(i,1)-ObstaclesWidth/2 ObstaclePositions(i,2)-ObstaclesWidth/2; ...
          ObstaclePositions(i,1)+ObstaclesWidth/2 ObstaclePositions(i,2)-ObstaclesWidth/2; ...
          ObstaclePositions(i,1)+ObstaclesWidth/2 ObstaclePositions(i,2)+ObstaclesWidth/2; ...
          ObstaclePositions(i,1)-ObstaclesWidth/2 ObstaclePositions(i,2)+ObstaclesWidth/2], ...
        [0 ObstacleHeight]}, obs_colours);
end

%disp("Built Scenario");