files = {
    'UAV_PathPlanning_Simulator.m', ...
    'DefineScenarios.m', ...
    'BuildScenario.m', ...
    'PathPlanPlot.m', ...
    'RandomizePositions.m', ...
    'ComputeMetrics.m', ...
    'runner_VFH.m', ...
    'runner_APF.m', ...
    'runner_FL_APF_WF.m', ...
    'runner_FL_APF_WF_VO.m', ...
    'FIS_Plots.m', ...
    'MapBuildingViewer.m', ...
    'FIS_CPL.fis', ...
    'FIS_LML.fis', ...
    'Model_VFH.slx', ...
    'Model_APF.slx', ...
    'Model_FL_APF_WF.slx', ...
    'Model_FL_APF_WF_VO.slx'
};

allNames = {};
for i = 1:length(files)
    try
        [~, p] = matlab.codetools.requiredFilesAndProducts(files{i});
        allNames = [allNames, {p.Name}];
        fprintf('Checked: %s\n', files{i});
    catch err
        fprintf('FAILED on %s: %s\n', files{i}, err.message);
    end
end

allToolboxes = unique(allNames)